name: Feed Bigquery
on:
  pull_request:
    branches:
      - main
jobs:
  run-rake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
    - name: Install SQLite3 Gem
      run: gem install sqlite3 -v '~> 1.4.0'
    #- run: bundle exec rake update_bigquery_tables
    #  env:
    #    BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
    #    BIGQUERY_PROJECT: cross-teacher-services
    #    BIGQUERY_DATASET: dfe_reference_data
    - name: Convert Reference Data to SQLite
      run: bundle exec rake convert_to_sqlite
    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ github.head_ref }} reference_data_${{ github.head_ref }}.sqlite3 --notes "Reference data for ${{ github.head_ref }}"
    #- name: Upload SQLite Database
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: reference_data_db_${{ github.ref_name }}
    #    path: reference_data_${{ github.ref_name }}.sqlite3
